/* WITH TEMP1 AS (
    SELECT 
        S.NAME,
        G.GRADE,
        S.MARKS
    FROM STUDENTS AS S
    JOIN GRADES AS G
    ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
),
TEMP2 AS (
    SELECT 
        CASE WHEN GRADE >= 8 THEN NAME ELSE NULL END AS NAME,
        GRADE,
        MARKS
    FROM TEMP1
)
SELECT 
    NAME, GRADE, MARKS
FROM TEMP2
ORDER BY 
    GRADE DESC,
    CASE WHEN GRADE >= 8 THEN NAME END ASC,
    CASE WHEN GRADE < 8 THEN MARKS END ASC;
*/    
-- 2ND APPROACH:
SELECT 
    CASE WHEN G.GRADE >= 8 THEN S.NAME ELSE NULL END AS NAME,
    G.GRADE,
    S.MARKS

    FROM STUDENTS AS S 
        JOIN GRADES AS G
        ON S.Marks BETWEEN G.Min_Mark AND G.Max_Mark
        
    ORDER BY 
    G.GRADE DESC,
    CASE WHEN G.GRADE >= 8 THEN S.NAME END ASC,
    CASE WHEN G.GRADE < 8 THEN S.NAME END ASC
